Change endpoint from str to Url
Kixunil/payjoin pull request #28
Opened 2022-07-14 02:17 UTC by DanGould

Close #3

I question whether I did right by removing deserialize_borrow.

As an aside, bip21 looks like it will be accepted into rust-bitcoin now. percent-encoding seems to be part of that work rather than this.

2022-07-14 13:28 UTC, Kixunil requested changes
Thanks! Yeah, removing the lifetime and `deserialize_borrowed` was correct since `Url` can't reuse the buffer. I was thinking that a new string parameter might be added in the future but it seems unlikely and not worth having more lifetimes.

Panic must be definitely fixed, it's a DoS vector at worst.

2022-07-15 02:28 UTC, evanlinjin requested changes
Looks pretty good to me (based on my limited understanding of bip-78). Also, it would be cool to run `cargo fmt` before committing :)

2022-07-15 02:28 UTC, evanlinjin commented on bip78/src/uri.rs
> +                    Url::parse(&*Cow::try_from(value).map_err(InternalPjParseError::NotUtf8)?)
I also want to point out you don't technically need the deref `*` either. From my understanding, it basically forces ownership?

2022-07-15 03:39 UTC, DanGould commented
Panic, lifetime, style issues fixed. Ensure only  `http://....onion`s are allowed.

> Use it to manipulate query parameters (instead of hard-coding it). – @evanlinjin

I was looking for this yesterday, how'd you find it 😎 thanks, done.

> I also want to point out you don't technically need the deref * either. From my understanding, it basically forces ownership? – @evanlinjin 

We do need the deref  `*` to `match` on the _values_ `"0"` and `"1"`. Sidenote: It would have been nicer if the spec didn't use `pjos=0` and let us check for the mere presence of`dpjos` instead of parsing the argument. they make it worse by suggesting to use `disablepaymentsubsitution=true` so we've got digits and strings to parse. Inconsistency is a bother. I don't know of any implementation in the wild actually taking advantage of either, so perhaps the spec can be changed / version upgraded to check for boolean presence instead of parsing.

I have applied select cargo format changes to those within the scope of this review

2022-07-15 12:49 UTC, Kixunil commented on bip78/src/uri.rs
> +                    Url::parse(&*Cow::try_from(value).map_err(InternalPjParseError::NotUtf8)?)
It's just deref coercions.

2022-07-15 12:51 UTC, Kixunil commented
Took only a quick look, have to run, should be back in a few hours.

2022-07-15 16:32 UTC, Kixunil approved these changes
Loogs good! @evanlinjin would you like to review again?

2022-07-17 23:31 UTC, evanlinjin approved these changes
Everything looks good!

Nit: It seems there are unused imports? I personally use `cargo clippy`, but `cargo fix` can work as well.

2022-07-20 06:47 UTC, DanGould commented
Thank you for your reviews ⚡️

If there were a merge button for me to press I would press it, but I have no such ability

2022-07-20 09:39 UTC, Kixunil commented
Oh, forgot to click, had too much stuff yesterday. Thanks again!

2022-07-20 09:39 UTC, merged