bump Bitcoin v0.28.1
Kixunil/payjoin pull request #32
Opened 2022-08-02 00:33 UTC by DanGould

As far as I can tell these changes are necessary for a passing integration test. Before, it was getting stuck parsing the bip21 from string.

Depends [explicitly](https://github.com/DanGould/rust-payjoin/blob/b1f246a77c2b456ab00cfb50c545d2d55951b6ae/bip78/Cargo.toml#L24) on [bumping bitcoin in the bip21 repo](https://github.com/Kixunil/bip21/pull/6)

2022-08-02 07:53 UTC, Kixunil requested changes
As I said in the other issue, let's just wait for 0.29.

Also, `Div` is definitely wrong.

2022-08-02 07:53 UTC, Kixunil commented on bip78/src/fee_rate.rs
> +    type Output = FeeRate;
The unit doesn't make sense. `FeeRate` = `Amount` / `Weight`, so `FeeRate` / `Weight` should be `Amount` / (`Weight` ^ 2) and there's no such unit in Bitcoin.

2022-08-02 07:53 UTC, Kixunil commented on bip78/src/output_type.rs
> -}
I wanted to provide some way of output type matching but I guess we can remove it for now and revert later.

2022-08-14 07:03 UTC, Kixunil commented
0.29 is out if you'd like to go ahead.

2022-10-27 21:04 UTC, DanGould commented
closed by #36

2022-10-27 21:04 UTC, closed without merging